export enum ERROR_CODE {
  SIGN_IN_WRONG_PASSWORD,
  SIGN_IN_NOT_EXISTING_USER,
  REGISTRATION_UNFILLED_FIELD,
  REGISTRATION_SHORT_PASSWORD,
  REGISTRATION_MISMATCH_PASSWORD,
  REGISTRATION_INVALID_EMAIL,
}
